# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET https://api.open-meteo.com/v1/forecast?timezone=auto&current=temperature_2m,precipitation_probability,wind_speed_10m&latitude=52.52&longitude=13.41
